name: Node.js CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: npm test

    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: ./deploy.sh
